# HTTP STATUS

HTTP_SUCCESS = 200
HTTP_CREATED = 201
HTTP_SERVER_ERROR = 500
HTTP_BAD_REQUEST = 400

# MYSQL
DB_USER_NAME = 'root'
DB_PASSWORD = 'root123@'
DB_HOST = 'localhost:3306'
DATA_BASE = 'boticario'
DB_CONNECTION_STRING = 'mysql://' + DB_USER_NAME + ':' + DB_PASSWORD + '@' + DB_HOST + '/' + DATA_BASE

# TABLES
T_CASH_BACK = 'Cashback'
T_PURCHASE = 'Purchase'
T_PURCHASE_STATUS = 'Purchase_Status'
T_RESELLER = 'Reseller'


# CONTENTS
JSON_CONTENT = "application/json"

# MESSAGES
SUCCESS_MESSAGE = 'Success'
