"""empty message

Revision ID: f958658a3858
Revises: 
Create Date: 2020-08-09 20:46:59.457566

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f958658a3858'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Cashback', ['id_cashback'])
    op.alter_column('Purchase', 'purchase_status_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('Purchase', 'reseller_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.drop_index('purchase_status_id_idx', table_name='Purchase')
    op.drop_index('reseller_id_idx', table_name='Purchase')
    op.create_unique_constraint(None, 'Purchase', ['id_purchase'])
    op.create_unique_constraint(None, 'Purchase_Status', ['id_purchase_status'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Purchase_Status', type_='unique')
    op.drop_constraint(None, 'Purchase', type_='unique')
    op.create_index('reseller_id_idx', 'Purchase', ['reseller_id'], unique=False)
    op.create_index('purchase_status_id_idx', 'Purchase', ['purchase_status_id'], unique=False)
    op.alter_column('Purchase', 'reseller_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.alter_column('Purchase', 'purchase_status_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'Cashback', type_='unique')
    # ### end Alembic commands ###
