-- MySQL Script generated by MySQL Workbench
-- Tue Aug 11 22:13:24 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Reseller`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Reseller` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Reseller` (
  `id_reseller` BIGINT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `create_date` DATETIME NOT NULL,
  `salt_password` VARCHAR(128) NOT NULL,
  `hash_password` VARCHAR(256) NOT NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `cpf` VARCHAR(45) NOT NULL,
  `street` VARCHAR(255) NULL,
  `city` VARCHAR(255) NULL,
  `state` VARCHAR(64) NULL,
  `country` VARCHAR(255) NULL,
  `zip_code` CHAR(15) NULL,
  `phone` VARCHAR(25) NULL,
  `is_active` TINYINT NOT NULL,
  `last_updated` DATETIME NOT NULL,
  PRIMARY KEY (`id_reseller`),
  UNIQUE INDEX `id_UNIQUE` (`id_reseller` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Purchase_Status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Purchase_Status` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Purchase_Status` (
  `id_purchase_status` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NOT NULL,
  `is_active` TINYINT NOT NULL,
  PRIMARY KEY (`id_purchase_status`),
  UNIQUE INDEX `status_UNIQUE` (`status` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Purchase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Purchase` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Purchase` (
  `id_purchase` BIGINT NOT NULL AUTO_INCREMENT,
  `product_code` VARCHAR(45) NOT NULL,
  `product_price` DECIMAL(13,2) NOT NULL,
  `date` DATETIME NOT NULL,
  `reseller_id` BIGINT NOT NULL,
  `purchase_status_id` INT NOT NULL,
  `cash_back` DECIMAL(7,2) NOT NULL,
  PRIMARY KEY (`id_purchase`),
  INDEX `reseller_id_idx` (`reseller_id` ASC) VISIBLE,
  INDEX `purchase_status_id_idx` (`purchase_status_id` ASC) VISIBLE,
  CONSTRAINT `resseler_id`
    FOREIGN KEY (`reseller_id`)
    REFERENCES `mydb`.`Reseller` (`id_reseller`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `purchase_status_id`
    FOREIGN KEY (`purchase_status_id`)
    REFERENCES `mydb`.`Purchase_Status` (`id_purchase_status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cashback`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cashback` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cashback` (
  `id_cashback` INT NOT NULL AUTO_INCREMENT,
  `purchase_amount` DECIMAL(13,2) NOT NULL,
  `percentage` DECIMAL(7,2) NOT NULL,
  `is_active` TINYINT NOT NULL,
  PRIMARY KEY (`id_cashback`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
